const { SlashCommandBuilder } = require('discord.js');

const FUMO_LIST = [
    'https://fumo.website/img/001.jpg',
    'https://fumo.website/img/002.jpg',
    'https://fumo.website/img/004.jpg',
    'https://fumo.website/img/005.jpg',
    'https://fumo.website/img/006.jpg',
    'https://fumo.website/img/007.jpg',
    'https://fumo.website/img/008.jpg',
    'https://fumo.website/img/013.jpg',
    'https://fumo.website/img/014.jpg',
    'https://fumo.website/img/015.jpg',
    'https://fumo.website/img/023.jpg',
    'https://fumo.website/img/039.jpg',
    'https://fumo.website/img/040.jpg',
    'https://fumo.website/img/045.jpg',
    'https://fumo.website/img/056.jpg',
    'https://fumo.website/img/080.jpg',
    'https://fumo.website/img/081.jpg',
    'https://fumo.website/img/082.jpg',
    'https://fumo.website/img/1032.jpg',
    'https://fumo.website/img/1035.jpg',
    'https://fumo.website/img/1036.jpg',
    'https://fumo.website/img/124.jpg',
    'https://fumo.website/img/139.jpg',
    'https://fumo.website/img/168.jpg',
    'https://fumo.website/img/181.jpg',
    'https://fumo.website/img/196.jpg',
    'https://fumo.website/img/197.jpg',
    'https://fumo.website/img/236.jpg',
    'https://fumo.website/img/237.jpg',
    'https://fumo.website/img/278.jpg',
    'https://fumo.website/img/290.jpg',
    'https://fumo.website/img/310.jpg',
    'https://fumo.website/img/345.jpg',
    'https://fumo.website/img/346.jpg',
    'https://fumo.website/img/356.jpg',
    'https://fumo.website/img/364.jpg',
    'https://fumo.website/img/423.jpg',
    'https://fumo.website/img/424.jpg',
    'https://fumo.website/img/454.jpg',
    'https://fumo.website/img/489.jpg',
    'https://fumo.website/img/490.jpg',
    'https://fumo.website/img/491.jpg',
    'https://fumo.website/img/492.jpg',
    'https://fumo.website/img/493.jpg',
    'https://fumo.website/img/494.jpg',
    'https://fumo.website/img/523.jpg',
    'https://fumo.website/img/558.jpg',
    'https://fumo.website/img/593.jpg',
    'https://fumo.website/img/644.jpg',
    'https://fumo.website/img/685.jpg',
    'https://fumo.website/img/739.jpg',
    'https://fumo.website/img/740.jpg',
    'https://fumo.website/img/773.jpg',
    'https://fumo.website/img/807.jpg',
    'https://fumo.website/img/820.jpg',
    'https://fumo.website/img/821.jpg',
    'https://fumo.website/img/834.jpg',
    'https://fumo.website/img/835.jpg',
    'https://fumo.website/img/836.jpg',
    'https://fumo.website/img/837.jpg',
    'https://fumo.website/img/852.jpg',
    'https://fumo.website/img/897.jpg',
    'https://fumo.website/img/898.jpg',
    'https://fumo.website/img/899.jpg',
    'https://fumo.website/img/900.jpg',
    'https://fumo.website/img/918.jpg',
    'https://fumo.website/img/920.jpg',
    'https://fumo.website/img/921.jpg',
    'https://fumo.website/img/935.jpg',
    'https://fumo.website/img/936.jpg',
    'https://fumo.website/img/937.jpg',
    'https://fumo.website/img/938.jpg',
    'https://fumo.website/img/939.jpg',
    'https://fumo.website/img/983.jpg',
    'https://fumo.website/img/984.jpg'
];

module.exports = {
    data: new SlashCommandBuilder()
        .setName('fumo')
        .setDescription('Generates a fumo image or gif.'),

    async execute(interaction) {
        const randomFumo = FUMO_LIST[Math.floor(Math.random() * FUMO_LIST.length)];
        await interaction.reply({ files: [randomFumo] });
    }
};
